version: "3.8"
services:

  app:
    build: .
    volumes:
      - ./public:/usr/src/app/public:delegated
      - ./src:/usr/src/app/src:delegated
    tty: true
    labels:
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"

  traefik:
    image: "traefik:v2.8"
    command: "--api.insecure --providers.docker"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
